db {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://0.0.0.0:6543/wps_blog_db"
  url = ${?DB_URL}
  username = ""
  username = ${?DB_USERNAME}
  password = ""
  password = ${?DB_PASSWORD}

  pool {
    maximum-pool-size = 10
    minimum-idle = 2
    idle-timeout-ms = 300000
    max-lifetime-ms = 1800000
    connection-timeout-ms = 5000
    leak-detection-threshold-ms = 30000
  }
}

http-server {
  interface = "0.0.0.0"
  port = 9000
}

cache {
  tags-ttl-seconds = 3600
  about-ttl-seconds = 3600
  feed-ttl-seconds = 60
  max-entries = 100
}
